# Module

In [ ]:
A simple file with .py extension

In [ ]:
pandas 

In [2]:
import pandas
import numpy

### Moudules contains following components

In [ ]:
1. variables
2. Functions
3. Class names


In [ ]:
class ClassName:  #class
    pass


def function_name():  #function
    pass

x = 5    # variables
y = 6


### Important keywords

In [ ]:
1. import >> used to import modules, libraries, and packages
2. as     >> used to rename the modules, libraries, and packages
3. from   >> from ClassName import function_name  as fn

## Packages

In [ ]:
It is directory with python files(.py) and __init__.py

### to run the python file

In [ ]:
python file_name.py

In [3]:
def fibonacci():
    print('Fibonacci')
    return [0,1,1,2,3,5]

fibonacci()

Fibonacci


[0, 1, 1, 2, 3, 5]

In [4]:
fibonacci()

Fibonacci


[0, 1, 1, 2, 3, 5]

In [5]:
x = 20
y = 30

def multiplication(a,b):
    print('Multiplication Function')
    mul = a*b
    print(f'Multiplication of {a} and {b} is {mul}')
    return mul


multiplication(x,y)

Multiplication Function
Multiplication of 20 and 30 is 600


600

In [7]:
import re
import numpy
import seaborn
import pandas

In [ ]:
pandas 0.24.1   #2 year ago

pandas 1.9.5    # now

environment setting   >>>   

In [8]:
import pandas 

In [10]:
# pandas.read_csv('Medicalpremium.csv')

In [12]:
import pandas as pd

In [14]:
# pd.read_csv('Medicalpremium.csv')

In [15]:
import numpy as np

In [16]:
np.array([3,5])

array([3, 5])

In [17]:
np.random.randint(10,20)

11

In [25]:
np.random.randint(10,20)

19

In [23]:
np.random.randint(10,20,2)

array([10, 13])

In [21]:
np.random.randint(100000,200000)

179008

In [22]:
np.random.randint(100000,200000)

150276

In [24]:
np.random.randint(10,20,2)

array([13, 11])

In [ ]:
import pandas as pd
pd.DataFrame()

In [ ]:
import pandas as pds
pds.DataFrame()

# VS code

In [ ]:

https://code.visualstudio.com › download

To open file with vs code >>> right click and open with code
or launch VS code and open file location

to open VS code terminal
use:
    control +  ~

In [26]:
import platform

In [27]:
dir(platform)

['_WIN32_CLIENT_RELEASES',
 '_WIN32_SERVER_RELEASES',
 '__builtins__',
 '__cached__',
 '__copyright__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_comparable_version',
 '_component_re',
 '_default_architecture',
 '_follow_symlinks',
 '_ironpython26_sys_version_parser',
 '_ironpython_sys_version_parser',
 '_java_getprop',
 '_libc_search',
 '_mac_ver_xml',
 '_node',
 '_norm_version',
 '_platform',
 '_platform_cache',
 '_pypy_sys_version_parser',
 '_sys_version',
 '_sys_version_cache',
 '_sys_version_parser',
 '_syscmd_file',
 '_syscmd_uname',
 '_syscmd_ver',
 '_uname_cache',
 '_ver_output',
 '_ver_stages',
 'architecture',
 'collections',
 'java_ver',
 'libc_ver',
 'mac_ver',
 'machine',
 'node',
 'os',
 'platform',
 'processor',
 'python_branch',
 'python_build',
 'python_compiler',
 'python_implementation',
 'python_revision',
 'python_version',
 'python_version_tuple',
 're',
 'release',
 'sys',
 'system',
 'system_alias',
 'un

In [28]:
x= platform.system()
x

'Windows'

In [30]:
x= platform.sys
x

<module 'sys' (built-in)>

In [31]:
x= platform.version()
x

'10.0.19041'

In [32]:

x= platform.processor()
x

'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel'