# Numpy Function

In [1]:
import numpy as np

# 1. shape

In [2]:
list1 = [1,2,45,3,5,4,5]
len(list1)

7

In [3]:
array1 =np.array([1,2,45,3,5,4,5])
len(array1)

7

In [4]:
array1 =np.array([1,2,45,3,5,4,5])
array1.shape

(7,)

In [22]:
array2 = np.array([5,4,2,7,8,6,4,6,8,7,8,9],ndmin=6)
print(array2)
print("Number of dimension: ",array2.ndim)
print("shape of array is :",array2.shape)

[[[[[[5 4 2 7 8 6 4 6 8 7 8 9]]]]]]
Number of dimension:  6
shape of array is : (1, 1, 1, 1, 1, 12)


In [9]:
array3 = np.array([[[2,3,4],[10,20, 9]]]]]]30],[100,200,300]],[[20,30,40],[50,40,60],[500,400,600]]])
print(array3)
print("Number of dimension: ",array3.ndim)
print("shape of array is :",array3.shape)

[[[  2   3   4]
  [ 10  20  30]
  [100 200 300]]

 [[ 20  30  40]
  [ 50  40  60]
  [500 400 600]]]
Number of dimension:  3
shape of array is : (2, 3, 3)


In [11]:
array3 = np.array([[[2,3,4],[10,20,30]],[[20,30,40],[50,40,60]]])
print(array3)
print("Number of dimension: ",array3.ndim)
print("shape of array is :",array3.shape)

[[[ 2  3  4]
  [10 20 30]]

 [[20 30 40]
  [50 40 60]]]
Number of dimension:  3
shape of array is : (2, 2, 3)


In [12]:
array3 = np.array([[[2,3,4,9],[10,20,30,96]],[[20,30,40,51],[50,40,60,78]]])
print(array3)
print("Number of dimension: ",array3.ndim)
print("shape of array is :",array3.shape)

[[[ 2  3  4  9]
  [10 20 30 96]]

 [[20 30 40 51]
  [50 40 60 78]]]
Number of dimension:  3
shape of array is : (2, 2, 4)


In [13]:
array3 = np.array([[[[2,3,4,9],[10,20,30,96]],[[20,30,40,51],[50,40,60,78]]]])
print(array3)
print("Number of dimension: ",array3.ndim)
print("shape of array is :",array3.shape)

[[[[ 2  3  4  9]
   [10 20 30 96]]

  [[20 30 40 51]
   [50 40 60 78]]]]
Number of dimension:  4
shape of array is : (1, 2, 2, 4)


In [15]:
array3 = np.array([[[[[2,3,4,9],[10,20,30,96]],[[20,30,40,51],[50,40,60,78]]]]])
print(array3)
print("Number of dimension: ",array3.ndim)
print("shape of array is :",array3.shape)

[[[[[ 2  3  4  9]
    [10 20 30 96]]

   [[20 30 40 51]
    [50 40 60 78]]]]]
Number of dimension:  5
shape of array is : (1, 1, 2, 2, 4)


# 2. Reshape

In [ ]:
used to convert array into n-D array

In [24]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
print("dimension is: ",array1.ndim)
print("shape is ",array1.shape)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]
dimension is:  1
shape is  (12,)


### 1D into 2D

In [ ]:
1*12=12
2*6 =12
3*4 =12
4*3 =12
6*2 =12
12*1=12

In [25]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(2,6)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 20, 16, 45]])

In [26]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(12,1)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [20],
       [16],
       [45]])

In [27]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(4,3)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [20, 16, 45]])

In [28]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(3,4)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 20, 16, 45]])

In [29]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(6,2)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 20],
       [16, 45]])

In [30]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(2,6)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 20, 16, 45]])

## 1D to 3D

In [31]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
print("dimension is: ",array1.ndim)
print("shape is ",array1.shape)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]
dimension is:  1
shape is  (12,)


In [ ]:
1*1*12
2*2*3
3*2*2
1*4*3
1*3*4
1*2*6

In [32]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(2,2,3)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[[ 2,  3,  4],
        [ 5,  6,  7]],

       [[ 8,  9, 10],
        [20, 16, 45]]])

In [33]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(1,4,3)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10],
        [20, 16, 45]]])

In [34]:
array1 = np.array([2,3,4,5,6,7,8,9,10,20,16,45]) #1D
print("array is: ",array1)
array1.reshape(1,2,6)

array is:  [ 2  3  4  5  6  7  8  9 10 20 16 45]


array([[[ 2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 20, 16, 45]]])