## Numpy Functions

In [1]:
import numpy as np

# 17. append

In [ ]:
np.append(array_name,value,axis)
values >> nD array
axis = 0 >>> rows
axis = 1 >>> columns

In [2]:
array1 = np.random.randint(10,20,size=10)
array1

array([15, 15, 11, 15, 17, 15, 15, 19, 18, 11])

In [3]:
array2=np.append(array1,1000)
array2

array([  15,   15,   11,   15,   17,   15,   15,   19,   18,   11, 1000])

In [7]:
array1=np.random.randint(1,10,size=5)
array2=np.random.randint(11,20,size=4)
print(array1)
print(array2)

[1 8 6 7 6]
[12 17 19 17]


In [9]:
new_arr=np.append(array1,array2)
print(array1)
print('*'*30)
print(array2)
print('*'*30)
print(new_arr)

[1 8 6 7 6]
******************************
[12 17 19 17]
******************************
[ 1  8  6  7  6 12 17 19 17]


In [10]:
array1=np.random.randint(1,10,size=(2,2))
array2=np.random.randint(11,20,size=(2,2))
print(array1)
print(array2)

[[7 5]
 [9 8]]
[[18 18]
 [19 11]]


In [11]:
new_arr=np.append(array1,array2,axis=0)
print(array1)
print('*'*30)
print(array2)
print('*'*30)
print(new_arr)

[[7 5]
 [9 8]]
******************************
[[18 18]
 [19 11]]
******************************
[[ 7  5]
 [ 9  8]
 [18 18]
 [19 11]]


In [12]:
new_arr=np.append(array1,array2,axis=1)
print(array1)
print('*'*30)
print(array2)
print('*'*30)
print(new_arr)

[[7 5]
 [9 8]]
******************************
[[18 18]
 [19 11]]
******************************
[[ 7  5 18 18]
 [ 9  8 19 11]]


### 18. concatenate

In [ ]:
np.concatenate(list_of_arrays,axis)
np.concatenate([array1,array2,....,arrayN],axis)

In [15]:
array1=np.random.randint(1,10,size=(2,2))
array2=np.random.randint(11,20,size=(2,2))
array3=np.random.randint(21,30,size=(2,2))
print("Array1\n",array1)
print("Array2\n",array2)
print("Array3\n",array3)

Array1
 [[2 4]
 [7 4]]
Array2
 [[16 18]
 [18 11]]
Array3
 [[22 26]
 [24 29]]


In [16]:
new_array=np.concatenate([array1,array2],axis=0)
new_array

array([[ 2,  4],
       [ 7,  4],
       [16, 18],
       [18, 11]])

In [17]:
new_array=np.concatenate([array1,array2],axis=1)
new_array

array([[ 2,  4, 16, 18],
       [ 7,  4, 18, 11]])

In [18]:
new_array=np.concatenate([array1,array2,array3],axis=0)
new_array

array([[ 2,  4],
       [ 7,  4],
       [16, 18],
       [18, 11],
       [22, 26],
       [24, 29]])

In [19]:
new_array=np.concatenate([array1,array2,array3],axis=1)
new_array

array([[ 2,  4, 16, 18, 22, 26],
       [ 7,  4, 18, 11, 24, 29]])

### 19. sort

In [20]:
array1=np.random.randint(30,70,size=10)
array1

array([30, 33, 31, 46, 43, 42, 69, 65, 31, 65])

In [21]:
sorted_array=np.sort(array1)
sorted_array

array([30, 31, 31, 33, 42, 43, 46, 65, 65, 69])

In [22]:
array2=np.random.randint(11,20,size=(2,2))
sort_array=np.sort(array2)
sort_array

array([[11, 19],
       [15, 17]])

In [24]:
array1=np.random.randint(30,70,size=(3,4))
print("Array1 is: \n",array1)
sorted_array=np.sort(array1)
sorted_array

Array1 is: 
 [[38 64 67 63]
 [50 33 65 43]
 [53 37 35 68]]


array([[38, 63, 64, 67],
       [33, 43, 50, 65],
       [35, 37, 53, 68]])

### descending
-np.sort(-array)

In [25]:
array2=np.random.randint(11,20,size=(2,2))
sort_array=-np.sort(-array2)
sort_array

array([[13, 11],
       [17, 11]])

In [26]:
array1=np.random.randint(30,70,size=(3,4))
print("Array1 is: \n",array1)
sorted_array=-np.sort(-array1)
sorted_array

Array1 is: 
 [[50 45 42 67]
 [30 30 53 63]
 [58 39 58 36]]


array([[67, 50, 45, 42],
       [63, 53, 30, 30],
       [58, 58, 39, 36]])

### matrix addition

In [ ]:
mat1=np.array([[2,5],[6,7]])
mat2=np.array([[5,4],[9,7]])

7 9 
15 14

In [27]:
mat1=np.array([[2,5],[6,7]])
mat2=np.array([[5,4],[9,7]])

mat1+mat2

array([[ 7,  9],
       [15, 14]])

## np.add

In [28]:
mat1=np.array([[2,5],[6,7]])
mat2=np.array([[5,4],[9,7]])
print('mat1 is \n',mat1)
print('mat2 is \n',mat2)
np.add(mat1,mat2)

mat1 is 
 [[2 5]
 [6 7]]
mat2 is 
 [[5 4]
 [9 7]]


array([[ 7,  9],
       [15, 14]])

### matrix multiplication

In [ ]:
mat1=np.array([[2,5],[6,7]])
mat2=np.array([[5,4],[9,7]])


2*5   5*4             10  20

6*9   7*7             54  49

In [29]:
mat1=np.array([[2,5],[6,7]])
mat2=np.array([[5,4],[9,7]])
print('mat1 is \n',mat1)
print('mat2 is \n',mat2)

mat1*mat2

mat1 is 
 [[2 5]
 [6 7]]
mat2 is 
 [[5 4]
 [9 7]]


array([[10, 20],
       [54, 49]])

### np.multiply

In [30]:
mat1=np.array([[2,5],[6,7]])
mat2=np.array([[5,4],[9,7]])
print('mat1 is \n',mat1)
print('mat2 is \n',mat2)

np.multiply(mat1,mat2)

mat1 is 
 [[2 5]
 [6 7]]
mat2 is 
 [[5 4]
 [9 7]]


array([[10, 20],
       [54, 49]])

### matrix dot product

In [31]:
mat1=np.array([[2,5],[6,7]])
mat2=np.array([[5,4],[9,7]])
print('mat1 is \n',mat1)
print('mat2 is \n',mat2)

mat3  0,0    0,1
      1,0    1,1

mat1 is 
 [[2 5]
 [6 7]]
mat2 is 
 [[5 4]
 [9 7]]


In [ ]:
mat3:
    0,0 = 2*5 + 5*9 =55
    0,1 = 2*4 + 5*7 = 43
    1,0 = 6*5 + 7*9 = 93
    1,1 = 6*4 +7*7  = 73
    
    
mat3   
55 43
93 73

In [32]:
mat1=np.array([[2,5],[6,7]])
mat2=np.array([[5,4],[9,7]])
print('mat1 is \n',mat1)
print('mat2 is \n',mat2)

np.dot(mat1,mat2)

mat1 is 
 [[2 5]
 [6 7]]
mat2 is 
 [[5 4]
 [9 7]]


array([[55, 43],
       [93, 73]])

### Mathematical operations

In [33]:
list1= [1,4,5,2,5]
list1*2

[1, 4, 5, 2, 5, 1, 4, 5, 2, 5]

In [35]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 + 10

Array1 is 
 [3 4 5 6 7 8 9]


array([13, 14, 15, 16, 17, 18, 19])

In [36]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 * 2

Array1 is 
 [3 4 5 6 7 8 9]


array([ 6,  8, 10, 12, 14, 16, 18])

In [38]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 -10

Array1 is 
 [3 4 5 6 7 8 9]


array([-7, -6, -5, -4, -3, -2, -1])

In [39]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 -3

Array1 is 
 [3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6])

In [40]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 / 2

Array1 is 
 [3 4 5 6 7 8 9]


array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [41]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 // 2

Array1 is 
 [3 4 5 6 7 8 9]


array([1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [42]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 ** 2

Array1 is 
 [3 4 5 6 7 8 9]


array([ 9, 16, 25, 36, 49, 64, 81])

In [43]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 % 2

Array1 is 
 [3 4 5 6 7 8 9]


array([1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [44]:
array1 = np.array([3,4,5,6,7,8,9])
print('Array1 is \n',array1)
array1 **4

Array1 is 
 [3 4 5 6 7 8 9]


array([  81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

# np.floor

In [47]:
array1 = np.array([[3.56,8.9,6.78],[10.35,8.79,5.6]])
print(array1)
array2=np.floor(array1)
array2

[[ 3.56  8.9   6.78]
 [10.35  8.79  5.6 ]]


array([[ 3.,  8.,  6.],
       [10.,  8.,  5.]])

In [ ]:
2  2.1  2.2 .......2.9 3    floor =2   ceiling =3

In [48]:
np.floor(4.9)

4.0

In [49]:
np.floor(4.1)

4.0

### np.ceil

In [50]:
np.ceil(4.9)

5.0

In [51]:
np.ceil(4.1)

5.0

In [52]:
array1 = np.array([[3.56,8.9,6.78],[10.35,8.79,5.6]])
print(array1)
array2=np.ceil(array1)
array2

[[ 3.56  8.9   6.78]
 [10.35  8.79  5.6 ]]


array([[ 4.,  9.,  7.],
       [11.,  9.,  6.]])

## np.around

In [54]:
array1 = np.array([[3.564258,8.9256,6.784587],[10.323655,8.72259,5.255856]])
print(array1)

[[ 3.564258  8.9256    6.784587]
 [10.323655  8.72259   5.255856]]


In [55]:
round(3.142567869,2)

3.14

In [56]:
np.around(3.142567869,2)

3.14

In [57]:
array1 = np.array([[3.564258,8.9256,6.784587],[10.323655,8.72259,5.255856]])
print(array1)
np.around(array1,2)

[[ 3.564258  8.9256    6.784587]
 [10.323655  8.72259   5.255856]]


array([[ 3.56,  8.93,  6.78],
       [10.32,  8.72,  5.26]])

In [58]:
array1 = np.array([[3.564258,8.9256,6.784587],[10.323655,8.72259,5.255856]])
print(array1)
np.around(array1,3)

[[ 3.564258  8.9256    6.784587]
 [10.323655  8.72259   5.255856]]


array([[ 3.564,  8.926,  6.785],
       [10.324,  8.723,  5.256]])

## np.sqrt

In [59]:
array1=np.array([25,36,49,225,144,576,784,729])
np.sqrt(array1)

array([ 5.,  6.,  7., 15., 12., 24., 28., 27.])

In [61]:
age = np.random.randint(25,65,size =50)
print(age)
print('*'*30)
print('*'*30)
np.sqrt(age)

[60 60 25 56 51 27 25 26 25 39 25 36 63 52 37 51 42 52 27 42 41 39 28 49
 52 31 62 33 45 57 39 64 28 41 37 25 36 53 46 39 32 28 61 63 27 62 32 47
 37 62]
******************************
******************************


array([7.74596669, 7.74596669, 5.        , 7.48331477, 7.14142843,
       5.19615242, 5.        , 5.09901951, 5.        , 6.244998  ,
       5.        , 6.        , 7.93725393, 7.21110255, 6.08276253,
       7.14142843, 6.4807407 , 7.21110255, 5.19615242, 6.4807407 ,
       6.40312424, 6.244998  , 5.29150262, 7.        , 7.21110255,
       5.56776436, 7.87400787, 5.74456265, 6.70820393, 7.54983444,
       6.244998  , 8.        , 5.29150262, 6.40312424, 6.08276253,
       5.        , 6.        , 7.28010989, 6.78232998, 6.244998  ,
       5.65685425, 5.29150262, 7.81024968, 7.93725393, 5.19615242,
       7.87400787, 5.65685425, 6.8556546 , 6.08276253, 7.87400787])

In [62]:
np.sqrt(196)

14.0

## np.cbrt

In [63]:
np.cbrt(512)

8.0

In [65]:
age = np.random.randint(1000,3000,size =(3,4))
print(age)
print('*'*30)
print('*'*30)
np.cbrt(age)

[[2414 2163 1923 2783]
 [1684 1910 2695 1655]
 [1369 2532 2109 2909]]
******************************
******************************


array([[13.41464205, 12.93258991, 12.43540006, 14.06601476],
       [11.89727122, 12.40731445, 13.91616565, 11.82858149],
       [11.10370247, 13.62975033, 12.82405957, 14.27516841]])

## np.where

In [66]:
list1 = [4,2,3,5,1,6,8,5,4,5]
list1.index(5)

3

In [67]:
list1 = [4,2,3,5,1,6,8,5,4,5]
result = [i for i,val in enumerate(list1) if val == 5]
result

[3, 7, 9]

In [71]:
array1=np.array([4,2,3,5,1,6,8,5,4,5])
np.where(array1==5)[0]

array([3, 7, 9], dtype=int64)

In [74]:
array1=np.array([4,2,3,5,1,6,7,5,3,4,9,8,8,5,4,5])
np.where(array1==8)[0]

array([11, 12], dtype=int64)