# Linear Algebra

In [ ]:
2x + 5y = 10
3x + 8y = 20

x=-20
y= 10

In [1]:
2*-20 + 5*10

10

In [2]:
3*-20 + 8*10

20

In [ ]:
2x + 5y + 4z = 10
3x + 8y + 6z = 20
4x + 6y + 2z = 15

In [3]:
import numpy as np

In [ ]:
2x + 5y = 10
3x + 8y = 20

In [4]:
array1 = np.array([[2,5],[3,8]])
array2 = np.array([10,20])
print("array1 is\n",array1)
print("array2 is\n",array2)

array1 is
 [[2 5]
 [3 8]]
array2 is
 [10 20]


In [5]:
result =np.linalg.solve(array1,array2)
result

array([-20.,  10.])

In [ ]:
2x + 5y + 4z = 10
3x + 8y + 6z = 20
4x + 6y + 2z = 15

In [6]:
arrayA = np.array([[2,5,4],[3,8,6],[4,6,2]])
arrayB = np.array([10,20,15])
print("arrayA is\n",arrayA)
print("arrayB is\n",arrayB)
print('*'*30)
result =np.linalg.solve(arrayA,arrayB)
result

arrayA is
 [[2 5 4]
 [3 8 6]
 [4 6 2]]
arrayB is
 [10 20 15]
******************************


array([-8.33333333, 10.        , -5.83333333])

# Inverse of matrix

In [ ]:
Adjoint  =  transpose of cofactor matrix    |A| != 0


2  5
3  8        

In [ ]:
8  -5
-3  2

In [7]:
array_A = np.array([[2,5],[3,8]])
array_A

array([[2, 5],
       [3, 8]])

In [8]:
np.linalg.inv(array_A)

array([[ 8., -5.],
       [-3.,  2.]])

In [9]:
array_a=np.array([[2,5,4],[3,8,6],[4,6,2]])
np.linalg.inv(array_a)

array([[ 3.33333333e+00, -2.33333333e+00,  3.33333333e-01],
       [-3.00000000e+00,  2.00000000e+00, -6.34413157e-17],
       [ 2.33333333e+00, -1.33333333e+00, -1.66666667e-01]])