# Numpy-Trigonometry

In [1]:
import numpy as np

In [ ]:
1. np.sin()
2. np.cos()
3. np.tan()
4. np.deg2rad()
5. np.rad2deg
6. np.pi

In [ ]:
sin >> opp/hyp
cos >> adj /hyp
tan >> opp/adj

cosec >> hyp/opp >> 1/sin
sec   >> hyp/adj >> 1/cos
cot   >> adj / opp >> 1/tan

## np.pi

In [2]:
np.pi

3.141592653589793

In [6]:
import math
math.pi

3.141592653589793

In [ ]:
Pi =  180  sin

## 1. np.sin

In [7]:
np.sin(np.pi/6)

0.49999999999999994

In [8]:
np.sin(np.pi/4)

0.7071067811865476

In [9]:
sin_60=np.sin(np.pi/3)
sin_60

0.8660254037844386

In [10]:
sin_90=np.sin(np.pi/2)
sin_90

1.0

## 2. np.cos

In [11]:
cos_30 = np.cos(np.pi/6)
cos_30

0.8660254037844387

In [12]:
cos_45 = np.cos(np.pi/4)
cos_45

0.7071067811865476

## 3. np.tan

In [13]:
tan_60=np.tan(np.pi/3)
tan_60

1.7320508075688767

In [14]:
tan_45 = np.tan(np.pi/4)
tan_45

0.9999999999999999

### Degree to Radian

In [15]:
np.deg2rad(45)

0.7853981633974483

In [16]:
np.pi/4

0.7853981633974483

In [17]:
np.deg2rad(60)

1.0471975511965976

In [18]:
np.pi/3

1.0471975511965976

In [19]:
rad = np.array([0,30,45,60,90])
np.deg2rad(rad)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [20]:
np.sin(rad)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [21]:
np.cos(rad)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

### Radians to Degree

In [23]:
radians= np.array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])
radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [24]:
deg = np.rad2deg(radians)
deg

array([ 0.        , 30.00000025, 44.99999981, 59.99999993, 90.00000018])