# Numpy Logs

In [1]:
import numpy as np

In [ ]:
1. np.log()
2. np.log2()
3. np.log10()

## 1. np.log()

In [ ]:
natural log >> base e
it is the inverse of exponential function >>> log(exp(x))= x

In [2]:
array1=np.random.randint(10,40,size=10)
array1

array([17, 19, 14, 21, 37, 19, 37, 39, 27, 19])

In [3]:
array1=np.random.randint(10,40,size=10)
array1

array([2.83321334, 2.94443898, 2.63905733, 3.04452244, 3.61091791,
       2.94443898, 3.61091791, 3.66356165, 3.29583687, 2.94443898])

In [4]:
np.log(24)

3.1780538303479458

In [5]:
np.log(247)

5.5093883366279774

### log transformation

In [8]:
array1=np.random.randint(100,700,size=10)
print(array1)
print('*'*30)
print(np.log(array1))

[696 453 610 398 527 201 265 256 599 376]
******************************
[6.54534966 6.11589213 6.41345896 5.98645201 6.26720055 5.30330491
 5.57972983 5.54517744 6.3952616  5.92958914]


In [9]:
np.log(1)

0.0

## 2. np.log2()

In [10]:
np.log2(34)

5.087462841250339

In [11]:
np.log(1)

0.0

In [12]:
array1=np.random.randint(100,700,size=10)
print(array1)
print('*'*30)
print(np.log2(array1))

[382 411 292 275 570 168 390 569 358 485]
******************************
[8.57742883 8.68299458 8.18982456 8.10328781 9.15481811 7.39231742
 8.60733031 9.15228484 8.48381578 8.92184094]


## 3. np.log10()

In [14]:
np.log10(34)

1.5314789170422551

In [15]:
np.log2(34)

5.087462841250339

In [16]:
np.log(34)

3.5263605246161616

In [17]:
array1=np.random.randint(100,700,size=10)
print(array1)
print('*'*30)
print(np.log10(array1))

[632 257 507 490 280 514 235 415 494 203]
******************************
[2.80071708 2.40993312 2.70500796 2.69019608 2.44715803 2.71096312
 2.37106786 2.6180481  2.69372695 2.30749604]
