# Statistics

In [2]:
import numpy as np

# 1. mean()

In [ ]:
mean = np.sum()/ len_array

In [16]:
array1=np.array([8,6,3,4,5,9,2])
np.sum(array1)

37

In [17]:
sum([8,6,3,4,5,9,2])

37

In [18]:
37/7

5.285714285714286

In [20]:
array1=np.array([8,6,3,4,5,9,2])

mean =np.mean(array1)
print("Mean of an array is : ",mean)

Mean of an array is :  5.285714285714286


In [23]:
array1=np.array([8,6,3,4,5,9,2])

mean =np.mean(array1)
print("Mean of an array is : ",np.around(mean,2))

Mean of an array is :  5.29


# 2. Median

In [30]:
array1=np.array([8,6,3,4,5,9,2])
print(array1)

[8 6 3 4 5 9 2]


In [31]:
np.sort(array1)

array([2, 3, 4, 5, 6, 8, 9])

In [ ]:
[2,3,4,5,6,8,9]

In [ ]:
Median = 5

In [ ]:
[2,3,4,5,6,8]

In [25]:
(4+5)/2  #median =4.5

4.5

In [27]:
array1=np.array([8,6,3,4,5,9,2])
median= np.median(array1)
print('Median of array is :',median)

5.0

In [29]:
array1=np.array([8,6,3,4,5,2])
median= np.median(array1)
print('Median of array is :',median)

Median of array is : 4.5


In [32]:
array1=np.array([8,6,3,4,5,9,2,100,200])

mean =np.mean(array1)
print("Mean of an array is : ",np.around(mean,2))

Mean of an array is :  37.44


In [33]:
array1=np.array([8,6,3,4,5,2,100,200])
median= np.median(array1)
print('Median of array is :',median)

Median of array is : 5.5


In [34]:
array1=np.array([25,36,45,55,60,1000])

mean =np.mean(array1)
print("Mean of an array is : ",np.around(mean,2))

Mean of an array is :  203.5


In [35]:
array1=np.array([25,36,45,55,60,1000])
median= np.median(array1)
print('Median of array is :',median)

Median of array is : 50.0


# 3. std

In [ ]:
std = sum(X-Xmean)^2 /N

In [36]:
array1=np.array([8,6,3,4,5,9,2])
np.std(array1)

2.3733211036908783

In [37]:
arr= np.random.randint(10,30,size=20)
arr

array([15, 18, 26, 11, 26, 18, 27, 18, 13, 14, 16, 26, 27, 12, 16, 13, 18,
       14, 22, 13])

In [38]:
np.std(arr)

5.378429138698399

In [39]:
np.mean(arr)

18.15

# 4. var

In [ ]:
var=(std)^2

In [4]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
mean=3.5

In [5]:
np.var(arr)

2.9166666666666665

In [6]:
np.std(arr)

1.707825127659933

In [7]:
(1.707)**2

2.9138490000000004

# 5. max

In [8]:
array1=np.array([8,6,3,4,5,9,2])
np.max(array1)

9

# 6. min

In [9]:
array1=np.array([8,6,3,4,5,9,2])
np.min(array1)

2

# 7. mode

In [ ]:
most frequent value of an array

In [13]:
from scipy.stats import mode   #scientific python

In [16]:
array1=np.array([8,6,3,4,6,5,9,6,2])

In [24]:
m=stats.mode(array1)
m

ModeResult(mode=array([6]), count=array([3]))

In [23]:
array1=np.array([8,6,3,4,6,5,9,6,2])
mode = stats.mode(array1)
print('Mode of an array is: ',mode[0][0])

Mode of an array is:  6


In [27]:
array1=np.array([8,6,3,4,5,9,2])
mode = stats.mode(array1)
print('Mode of an array is: ',mode[0][0])

Mode of an array is:  2


In [28]:
arr=np.random.randint(10,20,size=(4,5))
arr

array([[19, 13, 14, 12, 15],
       [11, 11, 16, 12, 13],
       [15, 12, 18, 14, 12],
       [12, 15, 19, 15, 13]])

In [30]:
mode = stats.mode(arr)
print('Mode of an array is: ',mode)

Mode of an array is:  ModeResult(mode=array([[11, 11, 14, 12, 13]]), count=array([[1, 1, 1, 2, 2]]))


In [31]:
mode = stats.mode(arr)
print('Mode of an array is: ',mode[0][0])

Mode of an array is:  [11 11 14 12 13]


In [ ]:
all are used in imputing outliers and empty values 