# Pandas

In [ ]:
Pandas >> Python Data Analysis
import pandas as pd

### Two data structure in pandas

In [ ]:
1. DataFrame:
    2- Dimentional >>> rows and columns
2. series:
    1 -Dimentional >> only one column

# Pandas Functions

In [ ]:
1. df.columns
2. df.index
3. df.axes
4. df.dtypes
5. df.select_dtypes(include,exclude)
6. df.info()
7. df.describe()
8. df.shape

## Access Columns and Rows

1. df.iloc[row_index,col_index]
2. df.loc[row_lables,col_lables]
3. df[col_name]>> single colmn name20. np.append
4. df[[col1,col2,....colN]]>>> multiple col name
5. df[start_row_index,end_row_index] >>> :
    df[3:6]   >> 3,4,5 rows
6. df.head() >>> first N rows >> Def val is 5
7. df.tail() >>> lat N rows >> Def val is 5
8. pd.read_csv()
9. pd.read_excel()

## Use Cases

In [ ]:
1. Read csv,excel,json files
2. EDA Exploratory Data Analysis (50%)
3. Data Cleansing:
    Missing Values
    Outliers
4. Encoding:
    One hot encoding 
    Label Encoding
5. Feature Selection
6. Join Multiple tables

## How to create DataFrames

In [ ]:
1. Reading csv,excel,json files
2. Array(1-D or 2-D array)
3. Dictionary
4. List
5. Tuples
6. Series


In [2]:
import pandas as pd
import numpy as np

### 1. Array

In [3]:
array = np.random.randint(10,20,size=(10,4))
array

array([[18, 15, 11, 10],
       [17, 12, 18, 11],
       [14, 18, 11, 10],
       [14, 13, 12, 12],
       [14, 18, 18, 18],
       [10, 14, 11, 19],
       [11, 16, 19, 15],
       [15, 14, 19, 10],
       [14, 14, 10, 12],
       [15, 14, 17, 16]])

In [4]:
df =pd.DataFrame(array)
df

0   1   2   3
0  18  15  11  10
1  17  12  18  11
2  14  18  11  10
3  14  13  12  12
4  14  18  18  18
5  10  14  11  19
6  11  16  19  15
7  15  14  19  10
8  14  14  10  12
9  15  14  17  16

In [7]:
array = np.zeros((10,4),dtype=int)
print(array)
df =pd.DataFrame(array)
df

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  0  0  0
3  0  0  0  0
4  0  0  0  0
5  0  0  0  0
6  0  0  0  0
7  0  0  0  0
8  0  0  0  0
9  0  0  0  0

In [9]:
array = np.random.randint(10,20, size=10)
df=pd.DataFrame(array)
df

0
0  14
1  17
2  10
3  18
4  15
5  10
6  12
7  17
8  19
9  16

### 2. Df using List

In [10]:
list1=[2,4,5,6,7,8,9,5,4,2,5]
df1=pd.DataFrame(list1)
df1

0
0   2
1   4
2   5
3   6
4   7
5   8
6   9
7   5
8   4
9   2
10  5

In [12]:
list1=[[2,4,5,6,7,8,9,5,4,2,5],[2,56,5,6,7,8,9,5,4,2,5]]
df1=pd.DataFrame(list1)
df1

0   1   2   3   4   5   6   7   8   9   10
0   2   4   5   6   7   8   9   5   4   2   5
1   2  56   5   6   7   8   9   5   4   2   5

### 3. df using tuple

In [14]:
t1=(4,5,4,6,7,8)
df1=pd.DataFrame(t1)
df1

0
0  4
1  5
2  4
3  6
4  7
5  8

### 3. Create Df using Dict

In [16]:
d1= {'A':[2,3,4,5,9],
    'B':[10,20,50,60,40],
    'C':np.array([100,200,300,500,900]),
    'D':np.arange(100,105)}
d1
df2=pd.DataFrame(d1)
df2

A   B    C    D
0  2  10  100  100
1  3  20  200  101
2  4  50  300  102
3  5  60  500  103
4  9  40  900  104

In [17]:
d1= {'A':[2,3,4,5,9],
    'B':[10,20,50,60,40],
    'C':np.array([100,200,300,500,900]),
    'D':np.arange(100,105),
    'E':(1,2,3,4,5)}
d1
df2=pd.DataFrame(d1)
df2

A   B    C    D  E
0  2  10  100  100  1
1  3  20  200  101  2
2  4  50  300  102  3
3  5  60  500  103  4
4  9  40  900  104  5

### 4. Read csv file

In [18]:
df=pd.read_csv('movies_data.csv')
df

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
0                R      Crime       142   
1                R      Crime       175   
2                R      Crime       200   
3            PG-13     Action       152   
4                R      Crime       154   
..             ...        ...       ...   
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[979 rows x 6 columns]

### 5. Read Excel file

In [19]:
df =pd.read_excel('Emp_Records.xlsx')
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

# Pandas Functions

In [20]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [21]:
df.columns ##returns list of column names(lables)

Index(['Emp ID', 'First Name', 'Age in Yrs', 'Weight in Kgs', 'Age in Company',
       'Salary', 'City'],
      dtype='object')

In [22]:
df.index # Returns list of row names(lables)

RangeIndex(start=0, stop=100, step=1)

In [23]:
df.axes

[RangeIndex(start=0, stop=100, step=1),
 Index(['Emp ID', 'First Name', 'Age in Yrs', 'Weight in Kgs', 'Age in Company',
        'Salary', 'City'],
       dtype='object')]

In [24]:
df.dtypes

Emp ID              int64
First Name         object
Age in Yrs        float64
Weight in Kgs       int64
Age in Company    float64
Salary              int64
City               object
dtype: object

In [25]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [27]:
df.isna().sum()

Emp ID            0
First Name        0
Age in Yrs        0
Weight in Kgs     0
Age in Company    0
Salary            0
City              0
dtype: int64

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Emp ID          100 non-null    int64  
 1   First Name      100 non-null    object 
 2   Age in Yrs      100 non-null    float64
 3   Weight in Kgs   100 non-null    int64  
 4   Age in Company  100 non-null    float64
 5   Salary          100 non-null    int64  
 6   City            100 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 5.6+ KB


In [29]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [31]:
df.select_dtypes(include=float)

Age in Yrs  Age in Company
0        36.36           13.68
1        47.02            9.01
2        54.15            0.98
3        39.67           18.30
4        40.31            4.01
..         ...             ...
95       22.82            1.05
96       32.61            5.93
97       52.66           28.53
98       29.60            6.99
99       38.38            2.26

[100 rows x 2 columns]

In [32]:
df.select_dtypes(exclude=float)

Emp ID First Name  Weight in Kgs  Salary          City
0   677509       Lois             60  168251        Denver
1   940761     Brenda             60   51063     Stonewall
2   428945        Joe             68   50155  Michigantown
3   408351      Diane             51  180294      Hydetown
4   193819   Benjamin             58  117642       Fremont
..     ...        ...            ...     ...           ...
95  639892       Jose             89  129774        Biloxi
96  704709     Harold             77  156194  Carol Stream
97  461593     Nicole             60   95673       Detroit
98  392491    Theresa             57   51015      Mc Grath
99  495141      Tammy             55   93650          Alma

[100 rows x 5 columns]

In [33]:
df.select_dtypes(include=object)

First Name          City
0        Lois        Denver
1      Brenda     Stonewall
2         Joe  Michigantown
3       Diane      Hydetown
4    Benjamin       Fremont
..        ...           ...
95       Jose        Biloxi
96     Harold  Carol Stream
97     Nicole       Detroit
98    Theresa      Mc Grath
99      Tammy          Alma

[100 rows x 2 columns]

In [43]:
df.select_dtypes(include=object)

First Name          City
0        Lois        Denver
1      Brenda     Stonewall
2         Joe  Michigantown
3       Diane      Hydetown
4    Benjamin       Fremont
..        ...           ...
95       Jose        Biloxi
96     Harold  Carol Stream
97     Nicole       Detroit
98    Theresa      Mc Grath
99      Tammy          Alma

[100 rows x 2 columns]

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Emp ID          100 non-null    int64  
 1   First Name      100 non-null    object 
 2   Age in Yrs      100 non-null    float64
 3   Weight in Kgs   100 non-null    int64  
 4   Age in Company  100 non-null    float64
 5   Salary          100 non-null    int64  
 6   City            100 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 5.6+ KB


In [44]:
df.describe()

Emp ID  Age in Yrs  Weight in Kgs  Age in Company         Salary
count     100.00000  100.000000     100.000000      100.000000     100.000000
mean   547652.10000   39.238700      58.080000        8.978400  119738.090000
std    257664.16679   12.066252      12.294106        8.657358   46185.278194
min    134841.00000   21.100000      40.000000        0.020000   42005.000000
25%    328643.75000   28.177500      50.000000        2.152500   83979.750000
50%    497414.00000   37.595000      56.000000        6.435000  118049.500000
75%    766040.00000   49.900000      61.250000       13.762500  162509.250000
max    979607.00000   59.470000      90.000000       34.520000  197537.000000

## How to access the DataFrame Items

In [45]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [47]:
d1= {'A':[2,3,4,5,9],
    'B':[10,20,50,60,40],
    'C':np.array([100,200,300,500,900]),
    'D':np.arange(100,105),
    'E':(1,2,3,4,5),
    'Z':1000}
d1
df2=pd.DataFrame(d1)
df2

A   B    C    D  E     Z
0  2  10  100  100  1  1000
1  3  20  200  101  2  1000
2  4  50  300  102  3  1000
3  5  60  500  103  4  1000
4  9  40  900  104  5  1000

In [48]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [49]:
type(df['First Name'])

pandas.core.series.Series

In [50]:
df[['Emp ID','Salary']]

Emp ID  Salary
0   677509  168251
1   940761   51063
2   428945   50155
3   408351  180294
4   193819  117642
..     ...     ...
95  639892  129774
96  704709  156194
97  461593   95673
98  392491   51015
99  495141   93650

[100 rows x 2 columns]

In [51]:
df[['Emp ID','Salary','City']]

Emp ID  Salary          City
0   677509  168251        Denver
1   940761   51063     Stonewall
2   428945   50155  Michigantown
3   408351  180294      Hydetown
4   193819  117642       Fremont
..     ...     ...           ...
95  639892  129774        Biloxi
96  704709  156194  Carol Stream
97  461593   95673       Detroit
98  392491   51015      Mc Grath
99  495141   93650          Alma

[100 rows x 3 columns]

In [52]:
df['First Name']

0         Lois
1       Brenda
2          Joe
3        Diane
4     Benjamin
        ...   
95        Jose
96      Harold
97      Nicole
98     Theresa
99       Tammy
Name: First Name, Length: 100, dtype: object

In [53]:
df[['First Name']]

First Name
0        Lois
1      Brenda
2         Joe
3       Diane
4    Benjamin
..        ...
95       Jose
96     Harold
97     Nicole
98    Theresa
99      Tammy

[100 rows x 1 columns]

### Access Rows and Columns

### 1. iloc

In [ ]:
df.iloc[row_index , column_index]

In [54]:
df.iloc[:,:] #all rows and columns

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [55]:
df.iloc[2:5,:]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   

           City  
2  Michigantown  
3      Hydetown  
4       Fremont

In [57]:
df.iloc[2:5,1:5]

First Name  Age in Yrs  Weight in Kgs  Age in Company
2        Joe       54.15             68            0.98
3      Diane       39.67             51           18.30
4   Benjamin       40.31             58            4.01

In [58]:
df.iloc[1:20:2,:]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
1   940761     Brenda       47.02             60            9.01   51063   
3   408351      Diane       39.67             51           18.30  180294   
5   499687    Patrick       34.86             58           12.02   72305   
7   380086      Carol       59.12             40           34.52   60918   
9   162402      Diana       29.73             60            3.44   43010   
11  153989       Jack       22.21             61            0.56   82965   
13  301576      Wayne       21.10             87            0.02   92758   
15  528509      Paula       50.97             42           22.95  152654   
17  214352    Theresa       24.66             59            2.52  197537   
19  622406     Thomas       49.85             73           19.15   73862   

              City  
1        Stonewall  
3         Hydetown  
5        Macksburg  
7      Blanchester  
9   Eureka Springs  
11       Las Vegas  
13           Maida  
15      Beulaville  
17     Toeterville  
19       Dutchtown

In [59]:
df.iloc[:,1:3]

First Name  Age in Yrs
0        Lois       36.36
1      Brenda       47.02
2         Joe       54.15
3       Diane       39.67
4    Benjamin       40.31
..        ...         ...
95       Jose       22.82
96     Harold       32.61
97     Nicole       52.66
98    Theresa       29.60
99      Tammy       38.38

[100 rows x 2 columns]

In [60]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [61]:
df.iloc[2] #single row with all details

Emp ID                  428945
First Name                 Joe
Age in Yrs               54.15
Weight in Kgs               68
Age in Company            0.98
Salary                   50155
City              Michigantown
Name: 2, dtype: object

In [62]:
df.iloc[2:3] #single row

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2  428945        Joe       54.15             68            0.98   50155   

           City  
2  Michigantown

In [63]:
df   #(1,2)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [64]:
df.iloc[1,2]

47.02

In [65]:
df.iloc[0,6]

'Denver'

In [66]:
df.iloc[:5]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   

           City  
0        Denver  
1     Stonewall  
2  Michigantown  
3      Hydetown  
4       Fremont

In [68]:
df.iloc[:10,:2]

Emp ID First Name
0  677509       Lois
1  940761     Brenda
2  428945        Joe
3  408351      Diane
4  193819   Benjamin
5  499687    Patrick
6  539712      Nancy
7  380086      Carol
8  477616    Frances
9  162402      Diana

In [70]:
df.iloc[:5,[1,3,5,6]]

First Name  Weight in Kgs  Salary          City
0       Lois             60  168251        Denver
1     Brenda             60   51063     Stonewall
2        Joe             68   50155  Michigantown
3      Diane             51  180294      Hydetown
4   Benjamin             58  117642       Fremont

## 2. loc()

In [ ]:
df.loc[row_labels,column_lebels]

In [71]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [72]:
df.loc[1:4] #1,2,3,4 rows and all columns

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   

           City  
1     Stonewall  
2  Michigantown  
3      Hydetown  
4       Fremont

In [73]:
df.iloc[1:4]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   

           City  
1     Stonewall  
2  Michigantown  
3      Hydetown

In [77]:
df.loc[1:4,'First Name':'Age in Company'] #

First Name  Age in Yrs  Weight in Kgs  Age in Company
1     Brenda       47.02             60            9.01
2        Joe       54.15             68            0.98
3      Diane       39.67             51           18.30
4   Benjamin       40.31             58            4.01

In [78]:
df.loc[1:4,['First Name','Age in Company']]

First Name  Age in Company
1     Brenda            9.01
2        Joe            0.98
3      Diane           18.30
4   Benjamin            4.01

In [79]:
df.loc[[1,3,6],['First Name','Age in Company']]

First Name  Age in Company
1     Brenda            9.01
3      Diane           18.30
6      Nancy            0.87

In [80]:
df.loc[:,:]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [81]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

## df.head()

In [ ]:
# Returns first N rows, default value is 5

In [88]:
df.head() #5

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   

           City  
0        Denver  
1     Stonewall  
2  Michigantown  
3      Hydetown  
4       Fremont

In [90]:
df.head(3)  #3

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   

           City  
0        Denver  
1     Stonewall  
2  Michigantown

In [91]:
df.head(20)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
5   499687    Patrick       34.86             58           12.02   72305   
6   539712      Nancy       22.14             50            0.87   98189   
7   380086      Carol       59.12             40           34.52   60918   
8   477616    Frances       58.18             42           23.27  121587   
9   162402      Diana       29.73             60            3.44   43010   
10  231469      Ralph       42.50             80            8.29  118457   
11  153989       Jack       22.21             61            0.56   82965   
12  386158    Melissa       45.45             55            1.68  166892   
13  301576      Wayne       21.10             87            0.02   92758   
14  441771     Cheryl       59.47             47           26.69   92220   
15  528509      Paula       50.97             42           22.95  152654   
16  912990     Joshua       47.23             68           14.91  184896   
17  214352    Theresa       24.66             59            2.52  197537   
18  890290      Julia       58.08             56           12.43  141518   
19  622406     Thomas       49.85             73           19.15   73862   

              City  
0           Denver  
1        Stonewall  
2     Michigantown  
3         Hydetown  
4          Fremont  
5        Macksburg  
6          Atlanta  
7      Blanchester  
8          Delmita  
9   Eureka Springs  
10         Sabetha  
11       Las Vegas  
12   New Matamoras  
13           Maida  
14        Quecreek  
15      Beulaville  
16     New Douglas  
17     Toeterville  
18   Primm Springs  
19       Dutchtown

### df.tail()

In [ ]:
# Returns last N rows, default value is 5

In [92]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [93]:
df.tail()# last 5 rows

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma

In [94]:
df.tail(2)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

        City  
98  Mc Grath  
99      Alma

In [95]:
df.tail(20)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
80  623253       Ruby       48.79             48            0.07  174774   
81  225925       Paul       25.98             68            2.89   73526   
82  761821     Ernest       32.77             87            2.49  176675   
83  400173    Dorothy       33.55             57            3.58  179017   
84  802554       Ryan       24.01             65            2.91  106628   
85  476433    Lillian       42.79             55           17.65  149878   
86  533952      Kelly       42.21             53            4.07   51878   
87  623929      Jimmy       50.70             87            9.63  120631   
88  844177   Margaret       35.91             43            4.20  180107   
89  212893      Janet       37.62             60            4.61  114481   
90  185032     Eugene       37.84             59            2.64  122950   
91  867084    Deborah       39.77             54           15.41   52767   
92  969964     Janice       37.57             56            0.93  147641   
93  158666    Rebecca       56.00             55           34.32  160043   
94  489424    Phillip       39.43             82            1.56  181774   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

                       City  
80                   Margie  
81                  Glidden  
82             Saranac Lake  
83             Philadelphia  
84                  Jarreau  
85                  Wichita  
86                     Meno  
87                 Oriskany  
88            Richmond Dale  
89                    Miami  
90                   Racine  
91                  Atqasuk  
92  Whiteman Air Force Base  
93             Independence  
94                 Mapleton  
95                   Biloxi  
96             Carol Stream  
97                  Detroit  
98                 Mc Grath  
99                     Alma

# Add column and row lables

In [97]:
array=np.random.randint(20,40,size=(6,4))
array
df=pd.DataFrame()  #Empty dataframe
df

Empty DataFrame
Columns: []
Index: []

In [99]:
array=np.random.randint(20,40,size=(6,4))
df=pd.DataFrame(array)
df

0   1   2   3
0  21  26  23  30
1  34  28  37  33
2  34  20  35  27
3  35  31  39  37
4  38  33  28  25
5  29  22  32  25

In [100]:
array=np.random.randint(20,40,size=(6,4))
df=pd.DataFrame(array,columns=['a','b','c','d'])
df

a   b   c   d
0  22  39  27  33
1  30  28  26  36
2  20  23  38  33
3  21  21  35  37
4  37  24  26  29
5  31  22  37  37

In [101]:
list('abcd')

['a', 'b', 'c', 'd']

In [102]:
array=np.random.randint(20,40,size=(6,4))
df=pd.DataFrame(array,columns=list('abcd'))
df

a   b   c   d
0  32  36  24  29
1  29  36  25  39
2  21  25  29  29
3  37  30  29  32
4  34  20  25  36
5  31  20  36  22

In [103]:
list('python')

['p', 'y', 't', 'h', 'o', 'n']

In [106]:
array=np.random.randint(20,40,size=(6,4))
df=pd.DataFrame(array,columns=list('abcd'),index=list('python'))
df

a   b   c   d
p  29  20  24  32
y  28  25  20  31
t  31  39  29  29
h  38  21  35  36
o  38  23  25  29
n  33  38  36  24

In [108]:
df.loc['p':'h']

a   b   c   d
p  29  20  24  32
y  28  25  20  31
t  31  39  29  29
h  38  21  35  36

In [116]:
array=np.random.randint(20,40,size=(6,4))
df=pd.DataFrame(array,columns=list('ABCD'),index=list('PYTHON'))
df

A   B   C   D
P  38  37  37  26
Y  20  39  31  33
T  29  33  30  22
H  36  20  26  22
O  35  31  37  31
N  24  35  25  39

In [110]:
df.iloc[1:3,:]

A   B   C   D
Y  29  20  31  27
T  36  21  23  34

In [111]:
df.loc['Y':'T',:]

A   B   C   D
Y  29  20  31  27
T  36  21  23  34

In [117]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [118]:
df.index

Index(['P', 'Y', 'T', 'H', 'O', 'N'], dtype='object')

In [119]:
df.columns=list('PQRS')
df

P   Q   R   S
P  38  37  37  26
Y  20  39  31  33
T  29  33  30  22
H  36  20  26  22
O  35  31  37  31
N  24  35  25  39

In [120]:
df.index=list('python')
df

P   Q   R   S
p  38  37  37  26
y  20  39  31  33
t  29  33  30  22
h  36  20  26  22
o  35  31  37  31
n  24  35  25  39

In [121]:
df.shape   #shpe of dataframe

(6, 4)

In [122]:
df3=pd.read_csv('titanic.csv')
df3

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [123]:
df3.shape

(891, 12)

In [126]:
row_count=df3.shape[0]
print('Number of rows in data: ',row_count)

Number of rows in data:  891


In [127]:
cl_count=df3.shape[1]
print('Number of Columns in data: ',cl_count)

Number of Columns in data:  12


In [129]:
df3

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [130]:
df3.isna() #null values in true and flase format

PassengerId  Survived  Pclass   Name  Gender    Age  SibSp  Parch  \
0          False     False   False  False   False  False  False  False   
1          False     False   False  False   False  False  False  False   
2          False     False   False  False   False  False  False  False   
3          False     False   False  False   False  False  False  False   
4          False     False   False  False   False  False  False  False   
..           ...       ...     ...    ...     ...    ...    ...    ...   
886        False     False   False  False   False  False  False  False   
887        False     False   False  False   False  False  False  False   
888        False     False   False  False   False   True  False  False   
889        False     False   False  False   False  False  False  False   
890        False     False   False  False   False  False  False  False   

     Ticket   Fare  Cabin  Embarked  
0     False  False   True     False  
1     False  False  False     False  
2     False  False   True     False  
3     False  False  False     False  
4     False  False   True     False  
..      ...    ...    ...       ...  
886   False  False   True     False  
887   False  False  False     False  
888   False  False   True     False  
889   False  False  False     False  
890   False  False   True     False  

[891 rows x 12 columns]

In [131]:
df3.isna().sum() #sum of null values

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# unique()

In [133]:
df3

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [135]:
df3['Survived'].unique() #unique values

array([0, 1], dtype=int64)

In [136]:
df3['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [137]:
df3['PassengerId'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

# 2. nunique()

In [138]:
df3['Survived'].nunique() #number of unique values

2

In [139]:
df3['Embarked'].nunique()

3

In [141]:
df3['PassengerId'].nunique()

891

# 3. value_counts()

In [ ]:
# unique value and its count

In [142]:
df3['Survived'].value_counts()

0    547
1    344
Name: Survived, dtype: int64

In [143]:
df3['Age'].value_counts()

24.00    30
22.00    27
18.00    26
28.00    25
19.00    25
         ..
55.50     1
74.00     1
0.92      1
70.50     1
12.00     1
Name: Age, Length: 88, dtype: int64

In [145]:
df3

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [147]:
df3['Ticket'].value_counts()

CA. 2343             7
1601                 7
347082               7
3101295              6
347088               6
                    ..
350404               1
4135                 1
383121               1
244270               1
STON/O 2. 3101274    1
Name: Ticket, Length: 681, dtype: int64

In [148]:
df3['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64