# Encoding:
    String datatypes into numeric datatypes

Types of Encoding:
    1. label encoding/Integer encoding
    2. one hot encoding
    3. dummy encoding
    4. effect encoding
    5. binary encoding
    6. base N encoding
    7. Hash encoding
    8. Target Encoding

In [1]:
import numpy as np
import pandas as pd

In [7]:
df=pd.read_csv('autos_dataset.csv')
df

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19     3.4              10.0        102   
4            136         mpfi  3.19     3.4               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01     3.4              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

In [4]:
df_body_style=pd.get_dummies(df['body-style'],prefix='body-style')
df_body_style

body-style_convertible  body-style_hardtop  body-style_hatchback  \
0                         1                   0                     0   
1                         1                   0                     0   
2                         0                   0                     1   
3                         0                   0                     0   
4                         0                   0                     0   
..                      ...                 ...                   ...   
200                       0                   0                     0   
201                       0                   0                     0   
202                       0                   0                     0   
203                       0                   0                     0   
204                       0                   0                     0   

     body-style_sedan  body-style_wagon  
0                   0                 0  
1                   0                 0  
2                   0                 0  
3                   1                 0  
4                   1                 0  
..                ...               ...  
200                 1                 0  
201                 1                 0  
202                 1                 0  
203                 1                 0  
204                 1                 0  

[205 rows x 5 columns]

In [8]:
df=pd.get_dummies(df,columns=['body-style'])
df

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors drive-wheels engine-location  wheel-base  length  ...  \
0            two          rwd           front        88.6   168.8  ...   
1            two          rwd           front        88.6   168.8  ...   
2            two          rwd           front        94.5   171.2  ...   
3           four          fwd           front        99.8   176.6  ...   
4           four          4wd           front        99.4   176.6  ...   
..           ...          ...             ...         ...     ...  ...   
200         four          rwd           front       109.1   188.8  ...   
201         four          rwd           front       109.1   188.8  ...   
202         four          rwd           front       109.1   188.8  ...   
203         four          rwd           front       109.1   188.8  ...   
204         four          rwd           front       109.1   188.8  ...   

     horsepower  peak-rpm  city-mpg highway-mpg  price  \
0           111      5000        21          27  13495   
1           111      5000        21          27  16500   
2           154      5000        19          26  16500   
3           102      5500        24          30  13950   
4           115      5500        18          22  17450   
..          ...       ...       ...         ...    ...   
200         114      5400        23          28  16845   
201         160      5300        19          25  19045   
202         134      5500        18          23  21485   
203         106      4800        26          27  22470   
204         114      5400        19          25  22625   

     body-style_convertible body-style_hardtop body-style_hatchback  \
0                         1                  0                    0   
1                         1                  0                    0   
2                         0                  0                    1   
3                         0                  0                    0   
4                         0                  0                    0   
..                      ...                ...                  ...   
200                       0                  0                    0   
201                       0                  0                    0   
202                       0                  0                    0   
203                       0                  0                    0   
204                       0                  0                    0   

    body-style_sedan  body-style_wagon  
0                  0                 0  
1                  0                 0  
2                  0                 0  
3                  1                 0  
4                  1                 0  
..               ...               ...  
200                1                 0  
201                1                 0  
202                1                 0  
203                1                 0  
204                1                 0  

[205 rows x 30 columns]

# OneHotEncoder

In [9]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [ ]:
1. fit()          #Training
2. fit_transform()  # Training
3. transform()       # Training and Testing

fit_transform >> fit + transform

In [12]:
onehot_enc=OneHotEncoder()
onehot_enc

OneHotEncoder()

In [13]:
df1=pd.DataFrame({"CITY":['Pune','Mumbai','Delhi','Kolkata','Mumbai','Delhi','Pune','Mumbai','Delhi','Delhi','Kolkata']})

In [14]:
df1

CITY
0      Pune
1    Mumbai
2     Delhi
3   Kolkata
4    Mumbai
5     Delhi
6      Pune
7    Mumbai
8     Delhi
9     Delhi
10  Kolkata

In [23]:
onehot_enc=OneHotEncoder(dtype=int)
onehot_enc.fit(df1[['CITY']])
onehot_enc.transform([['Pune']]).toarray()

array([[0, 0, 0, 1]])

In [29]:
array=onehot_enc.fit_transform(df1[['CITY']]).toarray()
array
df_city=pd.DataFrame(array,columns=onehot_enc.categories_)
df_city

Delhi Kolkata Mumbai Pune
0      0       0      0    1
1      0       0      1    0
2      1       0      0    0
3      0       1      0    0
4      0       0      1    0
5      1       0      0    0
6      0       0      0    1
7      0       0      1    0
8      1       0      0    0
9      1       0      0    0
10     0       1      0    0

In [28]:
# onehot_enc.categories_

In [30]:
onehot_enc.transform([['Pune']]).toarray()

array([[0, 0, 0, 1]])

In [31]:
onehot_enc.transform([['Mumbai']]).toarray()

array([[0, 0, 1, 0]])

In [33]:
# onehot_enc.transform([['PUNE']]).toarray()

# Fit + Transform

In [36]:
onehot_enc.fit(df1[['CITY']])
onehot_enc.transform(df1[['CITY']]).toarray()

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

# Train and Test Data

In [40]:
df1=pd.DataFrame({"CITY":['Pune','Mumbai','Delhi','Kolkata','Mumbai','Delhi','Pune','Mumbai','Delhi','Delhi','Kolkata']})
df1
x_train=df1.head(7)
x_train

CITY
0     Pune
1   Mumbai
2    Delhi
3  Kolkata
4   Mumbai
5    Delhi
6     Pune

In [42]:
x_test=df1.iloc[7:]
x_test

CITY
7    Mumbai
8     Delhi
9     Delhi
10  Kolkata

# Encoding on Training Dataset

In [44]:
OneHot_enc=OneHotEncoder(dtype=int)
x_train_res=OneHot_enc.fit_transform(x_train).toarray()
x_train_df=pd.DataFrame(x_train_res,columns=OneHot_enc.categories_)
x_train_df

Delhi Kolkata Mumbai Pune
0     0       0      0    1
1     0       0      1    0
2     1       0      0    0
3     0       1      0    0
4     0       0      1    0
5     1       0      0    0
6     0       0      0    1

# Encoding on Test Data

In [45]:
x_test_df=pd.DataFrame(OneHot_enc.transform(x_test).toarray(),columns=OneHot_enc.categories_)
x_test_df

Delhi Kolkata Mumbai Pune
0     0       0      1    0
1     1       0      0    0
2     1       0      0    0
3     0       1      0    0

In [46]:
import pickle

In [49]:
encoding=[onehot_enc,OneHot_enc]

In [50]:
with open("OneHot.pkl",'wb')as f:
    pickle.dump(encoding,f)